version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Installing test-utils...
      - mvn install -DskipTests -pl test-utils
      - echo Building servlet-http2 module...
      - mvn install -DskipTests -pl servlet/http2
artifacts:
  files:
    - servlet/http2/target/*.war
