version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building only servlet-http2 module...
      - mvn install -rf :servlet-http2
artifacts:
  files:
    - servlet/http2/target/*.war
