version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building project...
      - mvn clean package
artifacts:
  files:
    - servlet/http2/target/*.war
